language: ruby

rvm: 2.2.2

env:
  - DB=mysql

sudo: false

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rspec spec

notifications:
  email: false
  hipchat: 823d4c11858ce2bb9471e5b05d1925@678334
